### ISSUE TITLE
Man page not installed when building/installing on Debian

### ISSUE THREAD

**Issue by pandark** [apngasm/apngasm#46]
I followed the instructions for [building on Debian](https://github.com/apngasm/apngasm/blob/master/README.md#building-on-ubuntudebian-linux--) and everything apparently went fine, except `man apngasm` tells me there is no man entry for apngasm ([the man page](https://github.com/apngasm/apngasm/blob/master/docs/man/apngasm.1) has not been copied).

**Comment by Kagetsuki** [comment]
It's possible the man page was copied but to the wrong location. If I remember correctly we used some CMake magic command and we had some funny issue on OSX with it where it was copied to a place OSX was not including in its manual path. The thing is when I re-tested just now on Ubuntu it appears to be fine. Can do a quick search and see if "apngasm.1" was perhaps copied to some location that is not in your manual path?

**Comment by pandark** [comment]
There is no `apngasm.1` anywhere other than the source.

**Comment by Kagetsuki** [comment]
Thanks. I'll spin up a fresh Debian VM and give it a look when I have time - hopefully in the next few days.

**Comment by Kagetsuki** [comment]
@pandark Should be working now. I've added the manpage installation into the cmake directives. I believe it was there before but it seems to have gotten removed (bad merge at some point?).
