### ISSUE TITLE
x offset & y offset

### ISSUE THREAD

**Issue by canius** [apngasm/apngasm#49]
Why there is no x,y offset in APNGFrame ?

**Comment by Kagetsuki** [comment]
@canius I think you already figured it out but basically all frames need to be the same size. We built libapngasm with various interfaces so you can do things like combine libmagick and libapngasm and have libmagick feed libapngasm formatted frames all in the same size. There is a little bit of adjustment available in libapngasm but it's definitely not a multi-purpose utility library - it's specifically meant to assemble and dis-assemble APNG and any auxiliary functionality is coincidental.

If there's anything else we can help with please don't be afraid to ask! And of course if you notice even a small bug we really appreciate reports or patches.
