### ISSUE TITLE
libapngasm for OSX

### ISSUE THREAD

**Issue by brendanshean** [apngasm/apngasm#51]
I'm having issues installing libapngasm for OSX.  `brew install apngasm` works, but when I then run `gem install rapngasm -v '3.2.0'` I get the error message: `APNGAsm NOT found. Please install libapngasm.`  Do I need to do a build from source for libapngasm or is there something else I'm missing?  Thank you.

**Comment by Kagetsuki** [comment]
libapngasm gets installed along with apngasm (apngasm is just a frontend to libapngasm). We just tested and it seemed to work fine, but I have a suspicion. Can you go ahead and ```brew install swig``` and try again? Also, are you using macruby/system ruby?

**Comment by brendanshean** [comment]
Thank you for the response.  Swig was already installed via homebrew.  I'm using Ruby 2.3.

**Comment by Kagetsuki** [comment]
Very strange! Can you tell me what the response from ```apngasm -v``` is?

**Comment by brendanshean** [comment]
APNG Assembler v3.1.6 (frontend v3.1.6)

**Comment by brendanshean** [comment]
Here's the output log if you're curious:

$ gem install rapngasm -v '3.2.0'
Building native extensions.  This could take a while...
ERROR:  Error installing rapngasm:
ERROR: Failed to build gem native extension.

    current directory:
/Users/brendanshean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rapngasm-3.2.0/ext/rapngasm
/Users/brendanshean/.rbenv/versions/2.3.0/bin/ruby -r
./siteconf20160107-12343-1hvmpx0.rb extconf.rb
checking for main() in -lstdc++... yes
Checking for APNGAsm.checking for main() in -lapngasm... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You
may
need configuration options.

Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/Users/brendanshean/.rbenv/versions/2.3.0/bin/$(RUBY_BASE_NAME)
--with-stdc++lib
--without-stdc++lib
--with-apngasmlib
--without-apngasmlib
APNGAsm NOT found. Please install libapngasm.
To see why this extension failed to compile, please check the mkmf.log
which can be found here:


/Users/brendanshean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/rapngasm-3.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/Users/brendanshean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rapngasm-3.2.0
for inspection.
Results logged to
/Users/brendanshean/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/rapngasm-3.2.0/gem_make.out

**Comment by Kagetsuki** [comment]
That detailed output gives me a few hints. One of which being:
> Checking for APNGAsm.checking for main() in -lapngasm... no

Checking for main() is an issue specific to checking for dynamic libraries on OS-X. The thing is I was fairly certain we had fixed this but I guess not.

The second point is you are using rbenv which we have not checked on OSX (we have checked on linux BUT this was an rbenv built with dynamic support and not a vanilla rbenv).

I'll have someone with a mac take a look tomorrow. In the mean time would you mind trying to install it with macruby/system ruby once and seeing if you get the same output?

**Comment by brendanshean** [comment]
I appreciate it.  I ran with system Ruby and it failed, but I got different output this time:

$ gem install rapngasm -v '3.2.0'
Fetching: rapngasm-3.2.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rapngasm:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
checking for main() in -lstdc++... yes
Checking for APNGAsm.checking for main() in -lapngasm... yes
APNGAsm found, building RAPNGAsm.<stdin>:1:10: fatal error: 'apngasm-conf.h' file not found
#include <apngasm-conf.h>
         ^
1 error generated.

APNGAsm config header found in:
Generating native interface wrappers with SWIG
Using SWIG from /usr/local/bin/swig

Generating wrapper sources from /Library/Ruby/Gems/2.0.0/gems/rapngasm-3.2.0/ext/rapngasm/apngasm.i
/Library/Ruby/Gems/2.0.0/gems/rapngasm-3.2.0/ext/rapngasm/apng.i:85: Error: Unable to find 'apngasm-conf.h'
Wrappers generatedcreating Makefile

make "DESTDIR="
compiling apng_wrap.cxx
apng_wrap.cxx:1856:10: fatal error: 'apngasm.h' file not found
#include "apngasm.h"
         ^
1 error generated.
make: *** [apng_wrap.o] Error 1


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/rapngasm-3.2.0 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/rapngasm-3.2.0/ext/rapngasm/gem_make.out
-------

**Comment by Kagetsuki** [comment]
Aah, that's a little easier: system ruby isn't seeing where homebrew is installing headers. I remember encountering this issue before - if I recall correctly homebrew installs headers and things inside a location other than /usr/include or /usr/local/include and there was some way to make homebrew add its header location to the include path. Maybe it was just ```brew doctor``` that fixed it? I'll ask around to see if anyone knows off the top of their head.

We'll do our best to get back to you tomorrow [Japan time] with a fix (all the OS-X devs are asleep right now). I have a suspicion it's a combination of rbenv being static coupled with how OS-X checks dynamic libraries.

**Comment by brendanshean** [comment]
That makes sense.  I felt like it might have something to do with the path to the libapngasm.  El Capitan has changed some permission stuff that effected homebrew (e.g. http://digitizor.com/fix-homebrew-permissions-osx-el-capitan/).  Thank you so much for looking into this.

**Comment by brendanshean** [comment]
Unfortunately, `brew doctor` didn't solve it.

**Comment by Kagetsuki** [comment]
I hate to say it but we're having a really difficult time replicating this. I'm guessing it's an issue with homebrew not setting your paths correctly. You may want to try either manually exporting your load and include paths (LOAD_PATH and CPATH should do it?) or purging and re-installing homebrew. Worst case scenario I suspect a manual install of apngasm (clone -> ```mkdir build``` -> ```cd build``` -> ```cmake ..``` -> ```make``` -> ```sudo make install``) should work.

If you have another machine you can try this on and can replicate the error then that would indicate some other problem than a funky hombrew install. As for us we tried on 4 machines including one with rbenv static and couldn't replicate this.

PS: we tested on El Capitan and we think all homebrew installs were fresh on El Capitan. If your hombrew install pre-dates El Capitan then I suspect purging homebrew and re-installing could in fact be the "correct" solution.

**Comment by brendanshean** [comment]
Wow!  Thank you so much for looking into this.  While reinstalling homebrew and the manual install of apngasm did not work, the specifying the include paths was on the right track.  I had to try different flags with the gem install and finally got this one to work:
 
`gem install rapngasm -v 3.2.0 -- --with-opt-dir=/usr/local/Cellar/apngasm/3.1.6 --with-opt-include=/usr/local/Cellar/apngasm/3.1.6/include --with-opt-lib=/Users/brendanshean/apngasm/build/lib/ --srcdir=~/apngasm`

Thank you again for all of your help.

**Comment by Kagetsuki** [comment]
> the manual install of apngasm did not work
It was just pointed out to me that it's likely the dependencies to build/run apngasm would likely be installed using homebrew anyway, and if that was the case you should have encountered the same path errors that you did when trying to install rapngasm.

**Comment by brendanshean** [comment]
nokogiri and nokogumbo are the only other gems where I've had to include non-standard library paths (e.g.   `gem install nokogiri -v 1.6.7.1 -- --use-system-libraries  -- --with-xml2-include=/usr/local/Cellar/libxml2/2.9.2/include/libxml2 --with-xml2-lib=/usr/local/Cellar/libxml2/2.9.2/lib --with-xslt-lib=/usr/local/lib --with-xslt-include=/usr/local/include`)

As far as CPATH, LIBRARY_PATH, and LD_LIBRARY_PATH, I don't have any values for those in zsh.  Would they be somewhere else?

**Comment by Kagetsuki** [comment]
AHA! OK, those path variables should be in your environment and homebrew should be setting them. If you have those set then you won't have to manually specify where things are whenever you build a native gem. I'm guessing you're not sourcing a profile in your .zshrc or maybe you installed an extension or wrapper (like oh-my-zsh) and then forgot to import something. Try exporting a CPATH, LIBRARY_PATH, LD_LIBRARY_PATH and then doing a clean gem install on nokogiri and rapngasm *without* specifying locations with --with-xxx. If that works please tell me - and then add export lines to your .zshrc to avoid future headaches :grin:.

**Comment by brendanshean** [comment]
Hmm. I've seen these variables in Linux installations, but I've never heard or read of setting these values for homebrew (nor do any of the other devs I work with).  What values would you set these variables to?

**Comment by Kagetsuki** [comment]
CPATH will

**Comment by Kagetsuki** [comment]
These are fairly standard across platforms actually, and a wide variety of build tools look specifically for these when they search for libs and headers. The only reason you're having to specify --with-xxx is because you don't have these set with values that include where homebrew is installing libs and includes and the build tools, unable to find them in the hard-coded paths, are failing out.

**Comment by brendanshean** [comment]
I asked several other devs if they have any of these variables set and they do not.  Also, Google for CPATH, homebrew, etc. returns little relevant info (and most of what is shown is very outdated).  I'm fine with tweaking the install to get something to work, but arguing that these are standard for homebrew is simply not the case.

**Comment by Kagetsuki** [comment]
They're not standard for homebrew, they're just sot of "standard by default". You'll even have these set on windows if you deal with building a lot of things with tools like cmake.

Like I said, homebrew "should" be linking things it puts in its "cellar" into paths like /usr/local/include but apparently this isn't happening for you. If it was the issue of setting paths would never have come up. I know very little about homebrew so I'm not really sure why this is happening to you or what to do to make it happen.

**Comment by brendanshean** [comment]
Got it.  I see what you're saying now.  I appreciate you going out of your way to figure this out.  I will try these out and let you know if they work.

**Comment by Kagetsuki** [comment]
No problem - and I'm sure that someone else has either encountered this issue or could encounter it in the future so I'd like to leave a clear record of how to handle it.

Out of curiosity I looked into if CPATH and LIBRARY_PATH etc. are actually "standardized". They're not in a formal list of standard paths but rather they're defined by tools like dlopen which are essentially POSIX standard - so they're sort of an implied standard I guess? It also appears they are defined in the Windows list of standard environment variables - probably added about the time they decided to declare Windows as being "POSIX compliant" (despite the fact Windows is about as POSIX compliant as North Korea is a Free Democracy).

**Comment by brendanshean** [comment]
After updating my .zshrc with:

export CPATH=$CPATH:/usr/local/include
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

`gem install rapngasm -v 3.2.0` still failed with the same error message:
 APNGAsm NOT found. Please install libapngasm

**Comment by Kagetsuki** [comment]
Just to confirm: libapngasm is in fact located in /usr/local/lib?

**Comment by brendanshean** [comment]
Correct.

**Comment by Kagetsuki** [comment]
Really sorry to keep bothering you with this.
Can you provide me with the output of the following:
```
gem uninstall rapngasm
```
*uninstall all versions
```
gem install rapngasm --with-opt-include=/usr/local/include --with-opt-lib=/usr/local/lib
```
^output from this

Baiscally if that install line works it probably means either mkmf isn't looking at these env variables on OSX, or there is some sort of path precedence which is overriding said env variables.

If it does not work it means there's something funny with how libapngasm is being linked and I'm guessing that would be something that would need to be fixed in the brew recipe - which coincidentally was updated automatically during the last mid-version update so it's perfectly plausible that update was broken.

**Comment by brendanshean** [comment]
Same error as the original error message: 

APNGAsm NOT found. Please install libapngasm.

Only when I include the flag `srcdir=~/apngasm` does the gem install properly.

**Comment by Kagetsuki** [comment]
I'm assuming then you have a built apngasm/libapngasm in $HOME and therefore the following would also work:

```
gem install rapngasm --srcdir=~/apngasm
```

correct?

**Comment by brendanshean** [comment]
That is correct.

**Comment by Kagetsuki** [comment]
I have a strong suspicion this has to do with how homebrew is building the libraries. Can you give me the output of:
``` ls -la /usr/local/lib | grep libapngasm*```
and
```ldconfig -p | grep libapngasm```
and
```file /usr/local/lib/libapngasm*```

Again, really sorry to keep bothering you with this.

**Comment by brendanshean** [comment]
I would suspect it has something to do with homebrew.  Unfortunately, I did a clean install of El Capitan last night, so I can't replicate these issues anymore.  `gem install rapngasm` works fine without any flags.

**Comment by Kagetsuki** [comment]
I think you're correct on it being homebrew - more specifically I think it has to do with carrying an install of homebrew between upgrades. A few posts up when I asked you to try purging and re-installing homebrew was at the suggestion of our most experienced dev who works on a mac who basically said "system release upgrades break homebrew and brewdoctor rarely fixes it".

I really wish Apple would include a standard package system or would adopt homebrew officially. As it is it's like two different systems uncomfortably mashed together.

Anyway, thanks for hanging in through this. We just did a re-write of rapngasm so there's probably a few rough edges and almost no documentation - if you notice anything please don't hesitate to put up an issue on the rapngasm repository!

**Comment by brendanshean** [comment]
I completely agree.  One thing I miss from moving over from Linux is apt-get.  It just makes things easier in general.

I will let you know if I run into any other issues.  Thank you again for open sourcing this.
