### ISSUE TITLE
Frame order optimization

### ISSUE THREAD

**Issue by SoniEx2** [apngasm/apngasm#52]
Sometimes you want to use APNG for e.g. Minecraft recipes. A mode where it attempts to find the best frame order for highest compression would be nice. This would be optional, as a command line argument, because the images don't show up in the order you specify. It's most useful for Minecraft recipes and other similar types of... hmm... what can I call it? I'm not sure if "slideshow" fits here.

**Comment by Kagetsuki** [comment]
> because the images don't show up in the order you specify

Wait, this doesn't work?:
```apngasm -o outfile.png frame1.png frame2.png frame3.png [options]```

Or did you mean that globbing/wildcards don't work? EG:
```apngasm -o outfile.png frame*.png```

**Comment by SoniEx2** [comment]
I mean I want

`apngasm -o outfile.png frame*.png --reorder`

Reorder makes the images not show up in the order you specify, but rather show up in the optimal compression order. (I could use a shell script to generate a bunch of APNGs compiled with different frame orders and then compare their file sizes but I can't use a shell script from a java app)

**Comment by Kagetsuki** [comment]
Frame order shouldn't effect file size... are you finding that it is?

**Comment by SoniEx2** [comment]
It /can/, due to the way APNG does cross-frame elimination.

**Comment by Kagetsuki** [comment]
I guess I could see that but trying to fix it by re-ordering frames would not only make APNG files more complex to handle from a data perspective, it would also require something like n!^2 passes to brute-force find the most effective order - and even then I'm suspicious of how much that would decrease data-load vs say implementing more efficient compression. Again, if you have an idea and are willing to implement we'll be happy to look at any MR you put up - but again, it's not up to *me* what is accepted. Basically if you do implement this and the people who actually maintain the APNG "standard" say you're kludging it, which in this case I think they would, they're going to say no.

As for more efficient compression - can you give me some examples of where there's a significant difference in file size due only to frame order? I'd be interested in actually analyzing some real-world data.

**Comment by SoniEx2** [comment]
This has nothing to do with the APNG standard. This is just a way to make small APNGs from a set of images. Mainly useful for things like Minecraft recipes (to switch the input items), where **it doesn't matter in which order you *display* the images**.

**Comment by Kagetsuki** [comment]
If it doesn't matter what order you display the images in then why are you using an animation?

**Comment by SoniEx2** [comment]
Because you want the image to change, like a slideshow. APNG is a suitable format.

**Comment by Kagetsuki** [comment]
While it could be suitable for simple self-containment I'm curious what your deploy target is and specifically why size is such an issue. EG if you are so concerned specifically about size and you're deploying on the web then maybe it would be better to lay out all frames next to each-other in one large image and use CSS "sprite" animation to shift the frames. Of course that's assuming inner-image compression would actually be more efficient than cross-frame compression - which it likely would be but I doubt by much.

**Comment by SoniEx2** [comment]
Being able to download the image is a plus. Also generating a whole wiki from automated screenshots. I could re-run the program multiple times trying to find the best combination, but I'm sure you can come up with an algorithm to do it better than bruteforcing the whole thing (even if it's only marginally better).

**Comment by Kagetsuki** [comment]
What kind of size differences are we talking about? If it's only a few kB difference then maybe optimizing through a CDN or front end caching would have a much greater impact than trying to tackle core size issues.

**Comment by SoniEx2** [comment]
No recipes need frame order. Literally each frame is a different recipe for the same item.
