### ISSUE TITLE
Support No Loop

### ISSUE THREAD

**Issue by angelathewebdev** [apngasm/apngasm#54]
The minimum number of loops is 1 for now. Setting loops to 0 would result in infinite loops. How would user indicate that APNG should not loop

**Comment by sabberworm** [comment]
I think `1` essentially means that it only plays once:

> `num_plays` indicates the number of times that this animation should play
[(source)](https://wiki.mozilla.org/APNG_Specification#.60acTL.60:_The_Animation_Control_Chunk)

Note: it says “play”, not “loop”.

**Comment by Kagetsuki** [comment]
@sabberworm is correct.
