### ISSUE TITLE
Add support for packageconf

### ISSUE THREAD

**Issue by vflyson** [apngasm/apngasm#56]
GNU automake is unable to find the library via `pkg-config --libs libapngasm` but does so quite well for libpng, which supplies libpng.pc.in.
There may be another way to let pkg-config locate apngasm's library as a dependency, but it still feels like it could be a good addition to make the library easier to include.
Thank you.

**Comment by Kagetsuki** [comment]
We'd love to do that but none of us are particularly familiar with pkg-config/automake. At the moment we're very strained for resources so I don't think we'll be able to get around to it any time soon. We'd certainly appreciate a PR from someone who knows what they are doing though!

**Comment by Kagetsuki** [comment]
Closing this issue. If someone would like to submit a patch then we'll happily look at a pull request.
