### ISSUE TITLE
An option to Disassemble and then assemble without touching fdat zstream.

### ISSUE THREAD

**Issue by galaxy001** [apngasm/apngasm#60]
Inspired from <https://sourceforge.net/p/gif2apng/discussion/1022150/thread/74449fab/>, it is possible to use `pngout` to compress each frames with unchanged **Colour type** and given **Filter method**. And then *put them back together again "as is", without touching zstream inside.*

Would you add a function to:
1. Extract all frames with same minimal **Colour type** (Palette < Greyscale < Greyscale+A < RGB < RGBA). Recodering the xy`_offset` as well as `dispose_op` and `blend_op` in your *animation directive file*.
2. Merge png files above: Check all files to have same **Colour type** and **Filter method**, and then merge them without touching *zstream* inside.

So that we can use `pngout -c6` to compress those png frames and choose the best **output filter**.
Although we may need to try both `-f0` and `-f5` or even all the 6 "PNG output filter".

**Comment by Kagetsuki** [comment]
It may be possible, but there's a possibility there could be compatibility issues with some of the decoders out in the wild. Perhaps @maxstepin could provide a better analysis?

**Comment by maxstepin** [comment]
Let me think about it. Maybe it would be possible.

BTW, the internal logic of apngasm encoder is already trying both f0 and f5 filters, and selects the smaller one.

Meanwhile, you can try the legacy apngasm from sourceforge, even though it lacks some new features, it supports zopfli compression, which is slow, but quite competitive vs. pngout.
