### ISSUE TITLE
PPA installation errors for libapngasm, libpng16-16

### ISSUE THREAD

**Issue by philentology** [apngasm/apngasm#62]
Hey, I might be doing this totally wrong, but here goes:

Attempting to install apngasm on my docker ubuntu image via the ppa recommendation:

`$ add-apt-repository ppa:zero-tsuki/ppa`
`$ apt-get update`
`$ apt-get install apngasm`

Actual install attempt with -f to force the install.

```
# apt-get install -f -y apngasm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apngasm : Depends: libapngasm but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
```
# apt-get install -y -f libapngasm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libapngasm : Depends: libpng16-16 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
```
# apt-get install -f libpng16-16
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libpng16-16 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng16-16' has no installation candidate
```

I am by no means a ubuntu expert, so I'm quite possibly handling the ppa resource incorrectly.

Thanks!

**Comment by Kagetsuki** [comment]
Just to be clear before I go into this; this is probably not actually in issue with apngasm/libapngasm, it's very likely an issue with how your container is set up. Regardless I'd like to help you thorough this because we're increasingly deployment issues to these environments and I'd like to try and establish some clear solutions and write them out.

You're experiencing a chain of package dependency resolution errors. Basically apngasm needs libapngasm, but libapngasm needs libpng16-16, BUT I suspect the Ubuntu base repositories are not present on this container so it can't find that package. It's also possible the container you're using doesn't support package installation at runtime, only build time (this is a fairly common practice for container images you deploy to cloud services), so you'd have to do the whole installation in the Dockerfile.

Is this perhaps a non-standard Ubuntu container, but rather some specific container like say the Heroku16 container or something like that? If you can give me specifics like where you got the container/how you set it up I'll try and replicate the conditions you're experiencing this.

**Comment by philentology** [comment]
Hey @Kagetsuki, thank you for the suggestions. I am looking at what repositories are available.

My actual docker container is just a basic ubuntu image and I have successfully added other PPA installations (ffpmeg).

While I look to figure out the ubuntu repository with libpng16-16, heres a quick run down of the basics on my docker container and the sources list.

Dockerfile```
FROM ubuntu:14.04

RUN apt-get update -y

# important that all of these run to add repositories later on
RUN apt-get -y install apt-utils vim curl apache2 apache2-utils software-properties-common python-software-properties python3 libapache2-mod-wsgi-py3 git
RUN ln -sfn /usr/bin/python3 /usr/bin/python

# Enable wsgi once its added
RUN a2enmod wsgi reqtimeout

# Install PIP for Python3
RUN apt-get -y install python3-pip
RUN ln -sfn /usr/bin/pip3 /usr/bin/pipn

# Update PIP and install the copied requirements file
RUN pip install --upgrade pip
COPY requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt
COPY . /tmp/

# CLI tools: imagemagick, apngasm, ffmpeg
# ffmpeg
RUN add-apt-repository ppa:mc3man/trusty-media -y
RUN apt-get update -y
RUN apt-get install ffmpeg -y

# Get imagemagick (might need to make sure its on @6 but not sure how)
RUN apt-get install imagemagick -y

# APNGASM
RUN add-apt-repository ppa:zero-tsuki/ppa -y
RUN apt-get update -y
RUN apt-get install apngasm -y

# Add and enable the website config
ADD example.com.conf /etc/apache2/sites-available
RUN a2ensite example.com

RUN /etc/init.d/apache2 restart

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]
```
I can also bash in and run apt-get commands after build which I've done to do more debugging.

A list of my sources:
```
 See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.

deb http://archive.ubuntu.com/ubuntu/ trusty main restricted
deb-src http://archive.ubuntu.com/ubuntu/ trusty main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates main restricted

## Uncomment the following two lines to add software from the 'universe'
## repository.
## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ trusty universe
deb-src http://archive.ubuntu.com/ubuntu/ trusty universe
deb http://archive.ubuntu.com/ubuntu/ trusty-updates universe
deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates universe

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
# deb http://archive.ubuntu.com/ubuntu/ trusty-backports main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ trusty-backports main restricted

deb http://archive.ubuntu.com/ubuntu/ trusty-security main restricted
deb-src http://archive.ubuntu.com/ubuntu/ trusty-security main restricted
deb http://archive.ubuntu.com/ubuntu/ trusty-security universe
deb-src http://archive.ubuntu.com/ubuntu/ trusty-security universe
# deb http://archive.ubuntu.com/ubuntu/ trusty-security multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ trusty-security multiverse
```

And finally, the added PPA files:
```
/etc/apt/sources.list.d# ls -la
total 20
drwxr-xr-x 1 root root 4096 Nov 18 22:44 .
drwxr-xr-x 1 root root 4096 Nov 18 22:25 ..
-rw-r--r-- 1 root root  142 Nov 18 22:44 mc3man-trusty-media-trusty.list
-rw-r--r-- 1 root root  142 Nov 18 22:44 mc3man-trusty-media-trusty.list.save
-rw-r--r-- 1 root root  132 Nov 18 22:44 zero-tsuki-ppa-trusty.list
```

**Comment by philentology** [comment]
It looks like there is no 14.04 support: https://packages.ubuntu.com/search?keywords=libpng16-16

**Comment by Kagetsuki** [comment]
![image](https://user-images.githubusercontent.com/864634/33000729-2e59bb40-cded-11e7-965d-ccf06c51f6d8.png)
Here's probably the issue. The package stopped supporting 14.014 a little while ago. I'm sure it's still possible to build manually - let me see if I can edit your Dockerfile to do that. I'll try to get back to you by the end of the day JST.

**Comment by RoyiAvital** [comment]
What's the difference between this and the original [APNG Assembler](http://apngasm.sourceforge.net/)?
Namely, why did it get the "Next Generation" badge?

Thank You.

**Comment by Kagetsuki** [comment]
@RoyiAvital Please don't post in an existing issue. Next time create a new issue.
A: This is a port to/partial re-write in C++ as a library interface and a re-write of the CLI.

**Comment by Kagetsuki** [comment]
@philentology Sorry for the delay.

The manual build in a Dockerfile for 14.04 takes a very long time and I wouldn't recommend it/14.04 support is basically finished. Is there a reason you can't consider running on 16.04+?
