### ISSUE TITLE
Wrong Framerate

### ISSUE THREAD

**Issue by minikr** [apngasm/apngasm#66]
apngasm is creating apngs with the wrong frame rate for me.  Here is a list of delays and the resulting fps using ffprobe:
1 -> 322.03
2 -> 161.02
3 -> 107.34
5 -> 64.41
10 -> 32
20 -> 16.08
50 -> 6.42
100 -> 3.20
200 -> 1.54
300 -> 0.98
400 -> 0.71
500 -> 0.55
600 -> 0.42
700 -> 0.36
800 -> 0.31
900 -> 0.28
1000 -> 0.25
As far as I can tell, if x_1 and x_2 are delays, and y_1 and y_2 are the corresponding fps, (1/x_1 - 1/x_2)*(around 322) = (y_1 - y_2).  This happened in the homebrew version and when I built it from source.

System:  Mac os 10.12.6
apngasm version 3.1.6

**Comment by minikr** [comment]
Sorry, it turned out to be something on my end that was causing the issue.  I should have tested it more.

**Comment by Kagetsuki** [comment]
@minikr Thanks for the update! If you find any other issues please report. We're on "summer break" at the moment but we'll check things when we come back if you find anything else.
