### ISSUE TITLE
i want to set the first frame delay

### ISSUE THREAD

**Issue by hellozhangran** [apngasm/apngasm#67]
now the options can set the delay , and all frame will use the same delay。

but, i want set another delay at the first frame 

how to do that ?

**Comment by Kagetsuki** [comment]
It should work like this, as per the samples in ```apngasm --help```

```
Assemble an APNG with specific frame delays in miliseconds:

    apngasm -o outfile.png frame1.png 200 frame2.png 100 [options]

Assemble an APNG with specific frame delays in fractions of a second:

    apngasm -o outfile.png frame1.png 1:2 frame2.png 3:5 [options]
```

Please report if you have any issues with this.

If you are processing with a json specification file please say and I will post a sample.

**Comment by Kagetsuki** [comment]
I'm assuming this was solved? Please re-open if not.

**Comment by porg** [comment]
The manpage only mentions `--delay` which sets the default delay. But it doesn't mention that you can also set/override the delay individually per each frame! I only found that online here, and realized it's only shown in `--help`. Please rework the manpage. The manpage shall always contain all information whereas `-h --help` is the compact form of the manpage.
