### ISSUE TITLE
CMake Error: The source directory "/usr/local" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by Curioo** [apngasm/apngasm#68]
CMake Error: The source directory "/usr/local" does not appear to contain CMakeLists.txt.
i am getting this error ^^ how do i fix it? i followed exactly what the tutorial told me to do, im on OSX
![Screenshot 2019-06-15 at 19 56 11](https://user-images.githubusercontent.com/47332301/59554721-b033b580-8fa7-11e9-9395-1c51edb505e3.png)

**Comment by Kagetsuki** [comment]
You're in a directory that you don't (and shouldn't) have permissions to. Please return to your home directory with something like ```cd $h``` and re-clone there.
