### ISSUE TITLE
Option for heavier compression?

### ISSUE THREAD

**Issue by lukeroberts-tv** [apngasm/apngasm#69]
Is it possible to have an option for heaviest compression/optimization so I can get a smaller file size while retaining image quality? For example, I'd like to reduce this APNG file size if possible (it's currently 10.5 MB): https://imgur.com/a/0JYA8YT

**Comment by Kagetsuki** [comment]
There's a proposal to add newer compression in another issue but it's basically up to Max or someone else to implement it. The thing is I'm not sure it would really bring down the sample you have there in size that much - you may want to consider using a video format.
