### ISSUE TITLE
Move from boost filesystem to std::filesystem in c++ 17

### ISSUE THREAD

**Issue by AraHaan** [apngasm/apngasm#70]
I think this change could greatly improve maintainability and possibly reduce dependency on boost a little bit. Like so far it seems what you are doing with boost filesystem is currently in c++ 17 (for path class)

**Comment by AraHaan** [comment]
Also is it possible to somehow plug into image codecs on windows and somehow take over the default png codec that comes with windows so that way for any image loaded into windows forms or wpf or onto any gui picturebox it would animate properly?

**Comment by Kagetsuki** [comment]
While the suggestion is appreciated, we don't really have any need nor the resources to to make this improvement at this time. There's actually quite a lot that could be improved, so we'll add this to the list of "things to do".

As for Windows I'm not familiar with it, but I can tell you we haven't written any code for this so as far as I know as-is there is no facility for this.

**Comment by Kagetsuki** [comment]
@AraHaan This is an old issue and all but we've decided to put the time into implementing the move to std::filesystem. I'll close this issue as soon as the update has been rolled out.

**Comment by Kagetsuki** [comment]
The transition has been made and will be included in the next update.

**Comment by AraHaan** [comment]
👌
