### ISSUE TITLE
APNG does not get assembled correctly

### ISSUE THREAD

**Issue by flachware** [apngasm/apngasm#71]
Hi,

I’m using apngasm (v3.1.6 on macOS 10.15.3) to create a loading animation. However, the assembled APNG does not reflect the individual frames correctly. The frames consist of different opacity levels of one color, which seem to get superimposed in the APNG. For reasons of simplification I will just attach two frames here.

Is there some kind of optimization I have to disable?

![frame-01](https://user-images.githubusercontent.com/419747/77407759-f62f6c80-6db6-11ea-8f34-65bfffb80c49.png)
![frame-02](https://user-images.githubusercontent.com/419747/77407772-f891c680-6db6-11ea-93be-53d0b2982ab6.png)
![loading-small](https://user-images.githubusercontent.com/419747/77407783-faf42080-6db6-11ea-92f5-862384d4e02c.png)

**Comment by Kagetsuki** [comment]
Sorry for the delay. Can you please provide the full set of original frames and the full command you used to assemble them?

**Comment by flachware** [comment]
The pngs are exported with Adobe Illustrator, if this is of any concern.

**Comment by Kagetsuki** [comment]
The latest push by @maxstepin seems to have fixed this, so I'm merging it into the update_and_clean branch, which I'll be merging into master soon as it's about time we release. I did a few rounds of testing so I'm closing the issue for now, please check after the update and re-open if you still experience problems.

**Comment by Kagetsuki** [comment]
Actually I'll link this to the PR so it will be closed when accepted.
