### ISSUE TITLE
Missing vertical strip (-vs) option?

### ISSUE THREAD

**Issue by chrism** [apngasm/apngasm#74]
Hi,

I'm trying to follow the recommendation from the Sourceforge forum to reduce the number of colors to 256 (and filesize)

> But it's possible to create 8-bit apng files with my tools. 
apngdis APNG.png -s
It will create a vertical strip of all frames, in one file.
Use pngquant to optimize that file.
**Use apngasm with -vs (vertical strip input) option to create APNG, for example:
apngasm APNG-8bit.png APNG_strip.png -vs15**

https://sourceforge.net/p/apngasm/discussion/1151026/thread/f43198ed/#ad33

But I am unable to get the `-vs` option to work and cannot find any documentation on it.

Has it been removed?

Thanks

**Comment by Kagetsuki** [comment]
That's the other (original) version of apngasm, this is a port/library. I'm afraid we've never had that option in this version.
