### ISSUE TITLE
apngasm --output file fails if its path contains a relative link pointing to the upper directory (two dots unix style)

### ISSUE THREAD

**Issue by porg** [apngasm/apngasm#79]
My intent in human words:
- Change to the directory holding your animation files.
- Take all PNG files from this current directory and then
- create an animation output file in the directory above

And in command line syntax this is:
```
➜  ~ cd ~/Documents/Feedback/animation
➜  apngasm  *.png -o ../anim1.png -d 3000
./01.png => Delay=(3000/1000) sec
./02.png => Delay=(3000/1000) sec
./03.png => Delay=(3000/1000) sec
3 Frames
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::create_directories: Invalid argument
[1]    12405 abort      apngasm *.png -o ../anim1.png -d 3000
```

This seems to be valid syntax to me according to the manpage.
- But somehow apngasm seems to choke on it.
- APNG Assembler v3.1.6 on macOS 11.2.1 Big Sur

**Note**: I also detected #78 maybe the two are related and have an underlying bug of macOS Big Sur together?
Though #78 fails way later, actually it thinks it is successful (no errors or complaints) but creates no output file at all.

**Comment by porg** [comment]
@Kagetsuki
- 👍 Thanks for the instructions how to build, especially regarding filepaths.
- 😉 Even more glad that I do not need to test myself but that this is now available as a release 3.1.10

**Comment by porg** [comment]
- Just ran `brew update`. Then ran `brew outdated` among which `apngasm` is not yet listed.
- So when will release 3.1.10 be available on HomeBrew?
- Is this an automated process? Or some manual work involved in this?

**Comment by Deledrius** [comment]
> 
> 
>     * Just ran `brew update`. Then ran `brew outdated` among which `apngasm` is not yet listed.
> 
>     * So when will release 3.1.10 be available on HomeBrew?
> 
>     * Is this an automated process? Or some manual work involved in this?

I believe the updated formula will need to be created and accepted at [homebrew-core](https://github.com/Homebrew/homebrew-core/pulls) before the release becomes available through that channel.

**Comment by porg** [comment]
Ok. Thanks for the info!

**Comment by porg** [comment]
I do not really know the brew policies and workflows, if you could answer this to me please:
- What/who creates the respective pull request from `apngasm` to `homebrew-core` ? How are the two parties informing each other? Is the package maintainer informing them "He I have some worthy update to make it into your repository?" or is it the brew people who monitor the packages the include in their repo for updates, and from time to time include the relevant upgrades?
- If you query at `homebrew-core` for [is:pr apngasm in:title](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+apngasm+in%3Atitle) you see 2 from the past # 82958 from 2021-08-22 and # 85529 from 2021-09-19 and [none which is:open](https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aopen+apngasm+in%3Atitle+).
  - Do I understand this correctly that those two pull requests were so far the only times that an initial-install/update of `apngasm` was offered to `brew` users?

**Comment by Deledrius** [comment]
> 
> I do not really know the brew policies and workflows, if you could answer this to me please:
> 
I haven't done it myself, but they have [extensive documentation on contributions](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request).  I created an [update to the `apngasm` Formula](https://github.com/Homebrew/homebrew-core/compare/master...Deledrius:bump-apngasm-3.1.10), but did not yet open it as a Pull Request as there are linking errors that prevent it from completing the build.

The specification of `stdc++fs` in [lib/CMakeLists.txt](https://github.com/apngasm/apngasm/blob/master/lib/CMakeLists.txt#L71-L72) appears to be inappropriate for clang; removal allows the linking to continue, until it runs into additional errors when linking against icu.  It's likely one or more issues need to be created here to fix these problems before the Homebrew Formula can be successfully updated.

**Comment by Kagetsuki** [comment]
There's some packaging issues ran into I'm trying to fix before before I ask the Homebrew team to update.

@Deledrius Thanks for the heads up about stdc++fs. We didn't run into that in our OS-X testing but we don't actually have access to a modern OS-X machine and the one we tested on may not have a very standard setup. It seems to work as-is with clang on Linux. I'll try to replicate the problem today, and if I can't I'll try and add some conditions to cmake and put up a branch you can test building on.

Thanks for making your posts so detailed too, it makes it very easy for me to follow up!

**Comment by Kagetsuki** [comment]
It turns out the stdc++fs link doesn't need to be there at all (not sure if that's because I raised the C++ standard?), I pushed a branch ```adjust_packaging```, if someone could try and build/test on an OS-X machine that would be much appreciated.

* Re-opening the issue even though the content changed - if the new branch compiles cleanly I'll re-close it.

**Comment by Deledrius** [comment]
Glad to be of assistance.  I spent some time working on the problem today, and managed to get the build working on both a local macOS system as well as [Github's hosted macOS](https://github.com/Deledrius/apngasm/actions/runs/1424453016).  There appear to be some issues with the tests, even using the current master branch they don't run successfully for me on macOS, only Ubuntu.

**Comment by Kagetsuki** [comment]
The tests were always funny, and as they are the linking isn't actually being done the correct CMake way.

I hadn't even realized GH had an OS-X CI target. I'll have to take a look at that.

Thanks for the help, it's much appreciated.

**Comment by carlocab** [comment]
Just an FYI, there is an open PR to update apngasm at Homebrew: https://github.com/Homebrew/homebrew-core/pull/88825

We've run into the exact same build issues described above (i.e. linking with `stdc++fs` doesn't work). We'd be happy to update the formula as soon as this is resolved.

As for this question:

> * What/who creates the respective pull request from `apngasm` to `homebrew-core` ? 

Anyone can open pull requests to update formulae at homebrew-core. Version bumps are typically merged relatively quickly. Other more substantial changes require a little more review.

**Comment by Kagetsuki** [comment]
The build seems to be working now (with some platform specific commands), I'm going to close this issue but if anyone has problems with what's currently available in master on OS-X please don't hesitate to open a new issue for it.

**Comment by porg** [comment]
✅ Tested apngasm v3.1.10 installed via brew on macOS 13.7 and --output with a relative filepath now worked fine

```sh
$ sw_vers 
ProductName:		macOS
ProductVersion:		13.7
BuildVersion:		22H123

$ apngasm --version
APNG Assembler v3.1.10 (frontend v3.1.10)
# Installed via Homebrew

$ cd ~/Documents/Feedback/animation/

$ apngasm  *.png -o ../anim1.png -d 250 
./01.png => Delay=(250/1000) sec
./02.png => Delay=(250/1000) sec
./03.png => Delay=(250/1000) sec
./04.png => Delay=(250/1000) sec
./05.png => Delay=(250/1000) sec
./06.png => Delay=(250/1000) sec
./07.png => Delay=(250/1000) sec
./08.png => Delay=(250/1000) sec
./09.png => Delay=(250/1000) sec
./10.png => Delay=(250/1000) sec
./11.png => Delay=(250/1000) sec
./12.png => Delay=(250/1000) sec
./13.png => Delay=(250/1000) sec
13 Frames
../anim1.png
APNG assembled successfully => ../anim1.png

$ ffprobe ../anim1.png 

# Version and build info: Many lines long, removed from output. The essence is:

Input #0, apng, from '../anim1.png':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: apng, rgba(pc, gbr/unknown/unknown), 1440x800, 4 fps, 4 tbr, 100k tbn

$ qlmanage -p ../anim1.png 
Testing Quick Look preview with files:
	../anim1.png

# The animation is played back as a loop in QuickLook just fine.
```
