### ISSUE TITLE
Release 3.1.9

### ISSUE THREAD

**Issue by SMillerDev** [apngasm/apngasm#84]
https://code.launchpad.net/~zero-tsuki/+archive/ubuntu/ppa has a 3.1.9 release, but there is no tag here in this repo. Could you tag the repo as well? That way non-ubuntu users can also get a stable release from their distribution without doing weird things like in https://github.com/Homebrew/homebrew-core/pull/82958

**Comment by Kagetsuki** [comment]
It's not actually fully released. We need to fix installers for other platforms and test on other platforms, but our resources are limited.

**Comment by SMillerDev** [comment]
If you tag a release homebrew would love to test and distribute it.

**Comment by Kagetsuki** [comment]
@SMillerDev That's very much appreciated as none of my team are Apple devs and I don't think Max is either. Still we need to do some more dev to to release 2.1.9 properly and I'd really like to fit a little clean-up in as well.

Just let me apologize to everyone peeking in on this thread too - it's been very hard to dedicate time to this project. As a co-maintainer I feel guilty for putting off maintenance on this. I'll do my best to get put some time into the apngasm project again over the next month or so.

**Comment by SMillerDev** [comment]
Don't worry about time spent, it's open source. Everyone should just be glad you're doing something. I just wanted to understand what the state of the release was, so thanks for the help!
