### ISSUE TITLE
how to compile statically?

### ISSUE THREAD

**Issue by ioistired** [apngasm/apngasm#86]
I'm trying to compile my tool [tgs2apng](https://github.com/signalstickers/tgs2apng) statically. To do that I need .a files for libapngasm. How can I compile it statically? For `rlottie`, I just had to run `cmake -DBUILD_SHARED_LIBS=off ..`.

**Comment by Kagetsuki** [comment]
Sorry for the delay. I'm not sure how things were before but the update we're preparing has both static and dynamic output by default. Check this branch and please see if it works for you: https://github.com/apngasm/apngasm/tree/update_and_clean . If so please close the issue, and if not please tell us what issues you had.
