### ISSUE TITLE
filesystem.h missing?

### ISSUE THREAD

**Issue by ChuckM** [apngasm/apngasm#98]
Hi, this could be operator error and if so I apologize. Cloned the repo on my Ubunto 18.04 system, this seems to have 7.5 of GCC which doesn't include std::filesystem, instead it has an experimental version. Any chance of getting a back port?

**Comment by Kagetsuki** [comment]
Not operator error - and you have identified the problem correctly. Basically we used to be using Boost::Filesystem but that got mainlined as std::filesystem and we switched over. On some versions of GCC there was experimental support that could be enabled with some compiler flags, but it doesn't look like 7.5 is one of those versions. Essentially your only options would be to build an older version. The thing is there appears to be a build for Ubuntu 18.04.1 in the PPA, so I'd imagine there's some way to update GCC and build it (or of course you can add the PPA and install from there - but it may involve updating some of your packages which could be an issue if you have specific environment requirements). You can find the PPA [here](https://launchpad.net/~zero-tsuki/+archive/ubuntu/ppa).
